// Package codegen is the protoc-gen-angzarr core: it generates
// per-component dispatch wiring from proto service declarations carrying
// (angzarr.v1.component) options.
//
// For each declared component it emits, into Go:
//   - a STRICT handler interface (one typed method per declared rpc — a
//     missing handler is a compile error, never a silent no-op)
//   - a New<Component>Dispatch constructor that populates the engine's
//     dispatch table with unmarshal thunks calling the typed methods
//
// Generated code contains no dispatch logic and no gRPC — it is a thin
// table population over the hand-written engine (see engine.go), and the
// envelope stays google.protobuf.Any end to end.
//
// Generation-time validation (decided: taskloom deep-clerk): a
// (angzarr.v1.rejected).command value must be a fully-qualified message
// name that resolves in the compiled descriptor set; short names fail
// generation instead of silently never matching at runtime. Missing
// required component fields (state, domains) fail generation the same
// way — declaration errors surface before dispatch (spec C-0070..C-0075).
package codegen

import (
	"fmt"

	"google.golang.org/protobuf/compiler/protogen"
	"google.golang.org/protobuf/proto"
	"google.golang.org/protobuf/types/descriptorpb"
	"google.golang.org/protobuf/types/pluginpb"

	pb "github.com/benjaminabbitt/angzarr/client/go/proto/angzarr_client/proto/angzarr/v1"
)

const (
	angzarrPkg = protogen.GoImportPath("github.com/benjaminabbitt/angzarr/client/go")
	angzarrPb  = protogen.GoImportPath("github.com/benjaminabbitt/angzarr/client/go/proto/angzarr_client/proto/angzarr/v1")
	anypbPkg   = protogen.GoImportPath("google.golang.org/protobuf/types/known/anypb")
)

// Run is the protogen entry point: protoc-gen-angzarr's main wires it into
// protogen.Options{}.Run; tests and the godog validation harness drive it
// directly against in-memory CodeGeneratorRequests.
func Run(gen *protogen.Plugin) error {
	gen.SupportedFeatures = uint64(pluginpb.CodeGeneratorResponse_FEATURE_PROTO3_OPTIONAL)
	registry := messageRegistry(gen)
	for _, file := range gen.Files {
		if !file.Generate {
			continue
		}
		var components []*protogen.Service
		for _, svc := range file.Services {
			if componentOptions(svc) != nil {
				components = append(components, svc)
			}
		}
		if len(components) == 0 {
			continue
		}
		g := gen.NewGeneratedFile(file.GeneratedFilenamePrefix+"_angzarr.pb.go", file.GoImportPath)
		g.P("// Code generated by protoc-gen-angzarr. DO NOT EDIT.")
		g.P("// source: ", file.Desc.Path())
		g.P()
		g.P("package ", file.GoPackageName)
		g.P()
		for _, svc := range components {
			if err := generateComponent(g, registry, svc); err != nil {
				return fmt.Errorf("%s: %w", svc.Desc.FullName(), err)
			}
		}
	}
	return nil
}

// messageRegistry indexes every message in the compiled set by full name
// so state/rejected references resolve (or fail generation).
func messageRegistry(gen *protogen.Plugin) map[string]*protogen.Message {
	registry := make(map[string]*protogen.Message)
	var walk func(msgs []*protogen.Message)
	walk = func(msgs []*protogen.Message) {
		for _, m := range msgs {
			registry[string(m.Desc.FullName())] = m
			walk(m.Messages)
		}
	}
	for _, f := range gen.Files {
		walk(f.Messages)
	}
	return registry
}

func componentOptions(svc *protogen.Service) *pb.ComponentOptions {
	opts, ok := svc.Desc.Options().(*descriptorpb.ServiceOptions)
	if !ok || opts == nil {
		return nil
	}
	ext := proto.GetExtension(opts, pb.E_Component)
	component, _ := ext.(*pb.ComponentOptions)
	if component == nil || component.Kind == pb.ComponentKind_COMPONENT_KIND_UNSPECIFIED {
		return nil
	}
	return component
}

func methodOptions(m *protogen.Method) *descriptorpb.MethodOptions {
	opts, _ := m.Desc.Options().(*descriptorpb.MethodOptions)
	return opts
}

func rejectedOptions(m *protogen.Method) *pb.RejectedOptions {
	opts := methodOptions(m)
	if opts == nil {
		return nil
	}
	rejected, _ := proto.GetExtension(opts, pb.E_Rejected).(*pb.RejectedOptions)
	return rejected
}

func isApplier(m *protogen.Method) bool {
	opts := methodOptions(m)
	if opts == nil {
		return false
	}
	applies, _ := proto.GetExtension(opts, pb.E_Applies).(bool)
	return applies
}

func reactsOptions(m *protogen.Method) *pb.ReactsOptions {
	opts := methodOptions(m)
	if opts == nil {
		return nil
	}
	reacts, _ := proto.GetExtension(opts, pb.E_Reacts).(*pb.ReactsOptions)
	return reacts
}

// classified splits a component's rpcs into handlers/appliers/rejections.
type classified struct {
	handlers   []*protogen.Method
	appliers   []*protogen.Method
	rejections []*protogen.Method
}

func classify(svc *protogen.Service, registry map[string]*protogen.Message) (classified, error) {
	var c classified
	for _, m := range svc.Methods {
		rejected := rejectedOptions(m)
		switch {
		case rejected != nil:
			if err := validateFQ(registry, rejected.Command); err != nil {
				return c, fmt.Errorf("rpc %s: (angzarr.v1.rejected).command: %w", m.Desc.Name(), err)
			}
			c.rejections = append(c.rejections, m)
		case isApplier(m):
			c.appliers = append(c.appliers, m)
		default:
			c.handlers = append(c.handlers, m)
		}
	}
	return c, nil
}

// validateFQ enforces the deep-clerk contract at generation time.
func validateFQ(registry map[string]*protogen.Message, name string) error {
	if name == "" {
		return fmt.Errorf("missing command type")
	}
	if _, ok := registry[name]; !ok {
		return fmt.Errorf("%q is not a fully-qualified message name in the compiled set (short names never match rejection dispatch)", name)
	}
	return nil
}

func resolveState(registry map[string]*protogen.Message, component *pb.ComponentOptions, svc *protogen.Service) (*protogen.Message, error) {
	if component.State == "" {
		return nil, fmt.Errorf("(angzarr.v1.component).state is required for %v", component.Kind)
	}
	state, ok := registry[component.State]
	if !ok {
		return nil, fmt.Errorf("state %q is not a fully-qualified message name in the compiled set", component.State)
	}
	return state, nil
}

func generateComponent(g *protogen.GeneratedFile, registry map[string]*protogen.Message, svc *protogen.Service) error {
	component := componentOptions(svc)
	c, err := classify(svc, registry)
	if err != nil {
		return err
	}
	switch component.Kind {
	case pb.ComponentKind_COMPONENT_KIND_SAGA:
		return generateSaga(g, svc, component, c)
	case pb.ComponentKind_COMPONENT_KIND_AGGREGATE:
		state, err := resolveState(registry, component, svc)
		if err != nil {
			return err
		}
		return generateAggregate(g, svc, component, c, state)
	case pb.ComponentKind_COMPONENT_KIND_PROCESS_MANAGER:
		state, err := resolveState(registry, component, svc)
		if err != nil {
			return err
		}
		return generatePM(g, svc, component, c, state)
	case pb.ComponentKind_COMPONENT_KIND_PROJECTOR:
		state, err := resolveState(registry, component, svc)
		if err != nil {
			return err
		}
		return generateProjector(g, svc, component, c, state)
	default:
		return fmt.Errorf("unsupported component kind %v", component.Kind)
	}
}

// idents used across emitters
func ident(g *protogen.GeneratedFile, pkg protogen.GoImportPath, name string) string {
	return g.QualifiedGoIdent(pkg.Ident(name))
}

func generateSaga(g *protogen.GeneratedFile, svc *protogen.Service, component *pb.ComponentOptions, c classified) error {
	if component.InputDomain == "" || component.OutputDomain == "" {
		return fmt.Errorf("saga requires input_domain and output_domain")
	}
	name := svc.GoName
	dests := "*" + ident(g, angzarrPkg, "Destinations")
	cmdBook := "*" + ident(g, angzarrPb, "CommandBook")
	evtBook := "*" + ident(g, angzarrPb, "EventBook")
	notif := "*" + ident(g, angzarrPb, "Notification")
	rejn := "*" + ident(g, angzarrPb, "RejectionNotification")

	g.P("// ", name, "Handler is the strict business seam for the ", name, " saga.")
	g.P("// Every declared rpc must be implemented — a missing handler is a")
	g.P("// compile error, never a silent no-op.")
	g.P("type ", name, "Handler interface {")
	for _, m := range c.handlers {
		g.P("\t", m.GoName, "(event *", g.QualifiedGoIdent(m.Input.GoIdent), ", dests ", dests, ") ([]", cmdBook, ", []", evtBook, ", error)")
	}
	for _, m := range c.rejections {
		g.P("\t", m.GoName, "(n ", notif, ", rejection ", rejn, ") ([]", evtBook, ", error)")
	}
	g.P("}")
	g.P()
	g.P("// New", name, "Dispatch populates the engine saga table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "SagaDispatch"), " {")
	g.P("\treturn ", ident(g, angzarrPkg, "NewSagaDispatch"), "(", quote(string(svc.Desc.Name())), ", ", quote(component.InputDomain), ", ", quote(component.OutputDomain), ").")
	for i, m := range c.handlers {
		g.P("\t\tOnEvent(", quote(string(m.Input.Desc.FullName())), ", func(eventAny *", ident(g, anypbPkg, "Any"), ", dests ", dests, ") ([]", cmdBook, ", []", evtBook, ", error) {")
		g.P("\t\t\tevent := &", g.QualifiedGoIdent(m.Input.GoIdent), "{}")
		g.P("\t\t\tif err := eventAny.UnmarshalTo(event); err != nil { return nil, nil, ", ident(g, angzarrPkg, "AnyDecodeError"), "(eventAny.TypeUrl, err) }")
		g.P("\t\t\treturn h.", m.GoName, "(event, dests)")
		g.P("\t\t})", trailer(i, len(c.handlers), len(c.rejections) > 0))
	}
	for i, m := range c.rejections {
		g.P("\t\tOnRejected(", quote(rejectedOptions(m).Command), ", h.", m.GoName, ")", trailer(i, len(c.rejections), false))
	}
	g.P("}")
	g.P()
	return nil
}

func generateAggregate(g *protogen.GeneratedFile, svc *protogen.Service, component *pb.ComponentOptions, c classified, state *protogen.Message) error {
	if component.InputDomain == "" {
		return fmt.Errorf("aggregate requires input_domain (its own domain)")
	}
	name := svc.GoName
	statePtr := "*" + g.QualifiedGoIdent(state.GoIdent)
	evtBook := "*" + ident(g, angzarrPb, "EventBook")
	bizResp := "*" + ident(g, angzarrPb, "BusinessResponse")
	notif := "*" + ident(g, angzarrPb, "Notification")
	rejn := "*" + ident(g, angzarrPb, "RejectionNotification")
	cctx := ident(g, angzarrPkg, "CommandContext")

	g.P("// ", name, "Handler is the strict business seam for the ", name, " aggregate.")
	g.P("type ", name, "Handler interface {")
	for _, m := range c.handlers {
		g.P("\t", m.GoName, "(cmd *", g.QualifiedGoIdent(m.Input.GoIdent), ", state ", statePtr, ", cctx ", cctx, ") (", evtBook, ", error)")
	}
	for _, m := range c.appliers {
		g.P("\t", m.GoName, "(state ", statePtr, ", event *", g.QualifiedGoIdent(m.Input.GoIdent), ")")
	}
	for _, m := range c.rejections {
		g.P("\t", m.GoName, "(n ", notif, ", rejection ", rejn, ", state ", statePtr, ", cctx ", cctx, ") (", bizResp, ", error)")
	}
	g.P("}")
	g.P()
	g.P("// New", name, "Dispatch populates the engine aggregate table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "AggregateDispatch"), "[", statePtr, "] {")
	g.P("\trebuilder := ", ident(g, angzarrPkg, "NewRebuilder"), "(func() ", statePtr, " { return &", g.QualifiedGoIdent(state.GoIdent), "{} })")
	for _, m := range c.appliers {
		g.P("\trebuilder.Apply(", quote(string(m.Input.Desc.FullName())), ", func(state ", statePtr, ", payload *", ident(g, anypbPkg, "Any"), ") error {")
		g.P("\t\tevent := &", g.QualifiedGoIdent(m.Input.GoIdent), "{}")
		g.P("\t\tif err := payload.UnmarshalTo(event); err != nil { return err }")
		g.P("\t\th.", m.GoName, "(state, event)")
		g.P("\t\treturn nil")
		g.P("\t})")
	}
	g.P("\treturn ", ident(g, angzarrPkg, "NewAggregateDispatch"), "(", quote(string(svc.Desc.Name())), ", ", quote(component.InputDomain), ", rebuilder).")
	for i, m := range c.handlers {
		g.P("\t\tOnCommand(", quote(string(m.Input.Desc.FullName())), ", func(cmdAny *", ident(g, anypbPkg, "Any"), ", state ", statePtr, ", cctx ", cctx, ") (", evtBook, ", error) {")
		g.P("\t\t\tcmd := &", g.QualifiedGoIdent(m.Input.GoIdent), "{}")
		g.P("\t\t\tif err := cmdAny.UnmarshalTo(cmd); err != nil { return nil, ", ident(g, angzarrPkg, "AnyDecodeError"), "(cmdAny.TypeUrl, err) }")
		g.P("\t\t\treturn h.", m.GoName, "(cmd, state, cctx)")
		g.P("\t\t})", trailer(i, len(c.handlers), len(c.rejections) > 0))
	}
	for i, m := range c.rejections {
		g.P("\t\tOnRejected(", quote(rejectedOptions(m).Command), ", h.", m.GoName, ")", trailer(i, len(c.rejections), false))
	}
	g.P("}")
	g.P()
	return nil
}

func generatePM(g *protogen.GeneratedFile, svc *protogen.Service, component *pb.ComponentOptions, c classified, state *protogen.Message) error {
	// output_domain is the PM's own domain and its command-target domain
	// in one declaration (spec C-0072/C-0074): it feeds the engine's
	// pmDomain and stamps emitted commands.
	if component.OutputDomain == "" {
		return fmt.Errorf("process manager requires output_domain (its pm_domain and command-target domain)")
	}
	name := svc.GoName
	statePtr := "*" + g.QualifiedGoIdent(state.GoIdent)
	dests := "*" + ident(g, angzarrPkg, "Destinations")
	pmResp := "*" + ident(g, angzarrPb, "ProcessManagerHandleResponse")
	evtBook := "*" + ident(g, angzarrPb, "EventBook")
	notif := "*" + ident(g, angzarrPb, "Notification")
	rejn := "*" + ident(g, angzarrPb, "RejectionNotification")

	for _, m := range c.handlers {
		if reactsOptions(m).GetDomain() == "" {
			return fmt.Errorf("rpc %s: process-manager handler rpcs require (angzarr.v1.reacts).domain", m.Desc.Name())
		}
	}

	g.P("// ", name, "Handler is the strict business seam for the ", name, " process manager.")
	g.P("type ", name, "Handler interface {")
	for _, m := range c.handlers {
		g.P("\t", m.GoName, "(event *", g.QualifiedGoIdent(m.Input.GoIdent), ", state ", statePtr, ", dests ", dests, ") (", pmResp, ", error)")
	}
	for _, m := range c.appliers {
		g.P("\t", m.GoName, "(state ", statePtr, ", event *", g.QualifiedGoIdent(m.Input.GoIdent), ")")
	}
	for _, m := range c.rejections {
		g.P("\t", m.GoName, "(n ", notif, ", rejection ", rejn, ", state ", statePtr, ") ([]", evtBook, ", ", notif, ", error)")
	}
	g.P("}")
	g.P()
	g.P("// New", name, "Dispatch populates the engine PM table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "ProcessManagerDispatch"), "[", statePtr, "] {")
	g.P("\trebuilder := ", ident(g, angzarrPkg, "NewRebuilder"), "(func() ", statePtr, " { return &", g.QualifiedGoIdent(state.GoIdent), "{} })")
	for _, m := range c.appliers {
		g.P("\trebuilder.Apply(", quote(string(m.Input.Desc.FullName())), ", func(state ", statePtr, ", payload *", ident(g, anypbPkg, "Any"), ") error {")
		g.P("\t\tevent := &", g.QualifiedGoIdent(m.Input.GoIdent), "{}")
		g.P("\t\tif err := payload.UnmarshalTo(event); err != nil { return err }")
		g.P("\t\th.", m.GoName, "(state, event)")
		g.P("\t\treturn nil")
		g.P("\t})")
	}
	g.P("\treturn ", ident(g, angzarrPkg, "NewProcessManagerDispatch"), "(", quote(string(svc.Desc.Name())), ", ", quote(component.OutputDomain), ", rebuilder).")
	for i, m := range c.handlers {
		g.P("\t\tOnEvent(", quote(reactsOptions(m).GetDomain()), ", ", quote(string(m.Input.Desc.FullName())), ", func(eventAny *", ident(g, anypbPkg, "Any"), ", state ", statePtr, ", dests ", dests, ") (", pmResp, ", error) {")
		g.P("\t\t\tevent := &", g.QualifiedGoIdent(m.Input.GoIdent), "{}")
		g.P("\t\t\tif err := eventAny.UnmarshalTo(event); err != nil { return nil, ", ident(g, angzarrPkg, "AnyDecodeError"), "(eventAny.TypeUrl, err) }")
		g.P("\t\t\treturn h.", m.GoName, "(event, state, dests)")
		g.P("\t\t})", trailer(i, len(c.handlers), len(c.rejections) > 0))
	}
	for i, m := range c.rejections {
		g.P("\t\tOnRejected(", quote(rejectedOptions(m).Command), ", h.", m.GoName, ")", trailer(i, len(c.rejections), false))
	}
	g.P("}")
	g.P()
	return nil
}

func generateProjector(g *protogen.GeneratedFile, svc *protogen.Service, component *pb.ComponentOptions, c classified, state *protogen.Message) error {
	// A projector must declare which domains it subscribes to (spec
	// C-0075) — an undeclared subscription would silently receive nothing.
	if component.InputDomain == "" {
		return fmt.Errorf("projector requires input_domain (its subscribed domains)")
	}
	name := svc.GoName
	statePtr := "*" + g.QualifiedGoIdent(state.GoIdent)
	evtBook := "*" + ident(g, angzarrPb, "EventBook")
	projection := "*" + ident(g, angzarrPb, "Projection")

	g.P("// ", name, "Handler is the strict business seam for the ", name, " projector.")
	g.P("type ", name, "Handler interface {")
	for _, m := range c.handlers {
		g.P("\t", m.GoName, "(projection ", statePtr, ", event *", g.QualifiedGoIdent(m.Input.GoIdent), ") error")
	}
	g.P("\t// Finish packs the folded instance into the wire Projection.")
	g.P("\tFinish(projection ", statePtr, ", events ", evtBook, ") (", projection, ", error)")
	g.P("}")
	g.P()
	g.P("// New", name, "Dispatch populates the engine projector table from the proto declaration.")
	g.P("func New", name, "Dispatch(h ", name, "Handler) *", ident(g, angzarrPkg, "ProjectorDispatch"), "[", statePtr, "] {")
	g.P("\treturn ", ident(g, angzarrPkg, "NewProjectorDispatch"), "(", quote(string(svc.Desc.Name())), ", func() ", statePtr, " { return &", g.QualifiedGoIdent(state.GoIdent), "{} }).")
	g.P("\t\tForDomains(", quote(component.InputDomain), ").")
	for _, m := range c.handlers {
		g.P("\t\tOnEvent(", quote(string(m.Input.Desc.FullName())), ", func(projection ", statePtr, ", eventAny *", ident(g, anypbPkg, "Any"), ") error {")
		g.P("\t\t\tevent := &", g.QualifiedGoIdent(m.Input.GoIdent), "{}")
		g.P("\t\t\tif err := eventAny.UnmarshalTo(event); err != nil { return ", ident(g, angzarrPkg, "AnyDecodeError"), "(eventAny.TypeUrl, err) }")
		g.P("\t\t\treturn h.", m.GoName, "(projection, event)")
		g.P("\t\t}).")
	}
	g.P("\t\tFinish(h.Finish)")
	g.P("}")
	g.P()
	return nil
}

func quote(s string) string { return fmt.Sprintf("%q", s) }

// trailer continues the fluent chain when more registrations follow.
func trailer(i, n int, more bool) string {
	if i < n-1 || more {
		return "." // not last — keep chaining
	}
	return ""
}
